### ISSUE TITLE
Too many decimals error occurred with 4 decimal price precision

### ISSUE THREAD

**Issue by dligthart** [emspay/emswoocommerce#2]
Too many decimals error occurred with 4 decimal price precision.

Steps to reproduce:

1. Go to woocommerce settings
2. Enter 4 decimal precision
3. Order a product from the shop

Result:

From EMS Gateway:

"Your transaction may not be completed successfully
The cause of this error could be one of the following:
Too many decimal places in amount."

Expected result:

No error

**Comment by Chhaylin1844** [comment]
Steps to reproduce:
1.Go to woocommerce settings
2.Enter 4 decimal precision
3.Put environment to Integration (test)
4.Order a product from the shop

**Result**

From EMS Gateway:

"Your transaction may not be completed successfully
 The cause of this error could be one of the following:
 Too many decimal places in amount."

**Expected result**

No Error
