### ISSUE TITLE
Edit YITH WooCommerce EU VAT plugin [EST = 2.5h]

### ISSUE THREAD

**Issue by sereshqua** [emspay/emswoocommerce#6]

**Comment by enienaltowskidevpark** [comment]
[yith-woocommerce-eu-vat-premium_edited.zip](https://github.com/emspay/emswoocommerce/files/1348854/yith-woocommerce-eu-vat-premium_edited.zip)

Now in plugin settings, a user can specify countries for VAT exemption. A user can also change description under VAT number field.

**Comment by enienaltowskidevpark** [comment]
[yith-woocommerce-eu-vat-premium_edited_v1.1.zip](https://github.com/emspay/emswoocommerce/files/1358315/yith-woocommerce-eu-vat-premium_edited_v1.1.zip)

I made few changes and now user can select option if he wants to remove taxes from shipping cost too.

**Comment by dligthart** [comment]
@

**Comment by dligthart** [comment]
@e
