### ISSUE TITLE
EMS module is not working properly on the latest WooCommerce version

### ISSUE THREAD

**Issue by sereshqua** [emspay/emswoocommerce#7]
Decimal error shows up.

Users need to manually change the TAX settings to 'No, I will enter prices exclusive of tax' in order to fix the decimal error in WooCommerce settings

`It seems to be taking 4 decimals in the VAT settings and adding those 4 to the 2 pricing decimals. The subtotal value shows for example EUR 17.154632 which should be EUR 17.2 or 17.15
Checking the "round up subtotal amount" box is not working.
Could it be that since the woocommerce release this functionality in our plugin is not working anymore?`

**Comment by dligthart** [comment]
merchant updated woocommerce to 3.2.3 and is using EMS plugin 1.1.1.


[12:44] 
we receive an     N:SE2000:Authentication error


[12:44] 
something with the calling of the id and sending it to IPG...

**Comment by dligthart** [comment]
For one merchant: "His ideal tx all fail. This does not include credit card, it is mainly ideal that fails and generates the following error code:"

'mod_fcgid: stderr: id was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'),
do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, call_user_func_array, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment,
Emspay_Gateway->process_payment, Emspay_Gateway->save_emspay_meta, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: '

**This one seems to have been resolved**

**Comment by dligthart** [comment]
we are receiving more messages from merchants that after theu updated woocommerce to the latest deployment, the EMS module is not working properly anymore


[2:53] 
we then need to manually change the TAX settings to 'No, I will enter prices exclusive of tax' in order to fix the decimal error


[2:54] 
however, this is annoying, because almost all merchants are used to enter pricing as 'Yes, I will enter prices inclusive of tax'

**Comment by dligthart** [comment]
https://www.dropbox.com/s/whyc3c1m0mjs9lx/Screenshot%202017-11-13%2012.17.54.png?dl=0
